# Single Neuron Networks

In [1]:
import nnabla as nn
import nnabla.functions as F
import nnabla.parametric_functions as PF
import numpy as np
import nnabla.initializer as I
from save_nnp import save_nnp

import pprint

2020-05-05 16:46:58,601 [nnabla][INFO]: Initializing CPU extension...


In [2]:
import pathlib, os
data_directory='./models'
pathlib.Path(data_directory).mkdir(parents=True, exist_ok=True) 

## Affine

In [3]:
nn.parameter.clear_parameters()
rng = np.random.seed(2345)
initializer = I.UniformInitializer((-0.1, 0.1), rng=rng)

x_size = 5
x_range = (-1.0, 1.0)

x = nn.Variable((1, x_size))          # input tensor is just a vector of x_size floats
y = PF.affine(x, 1, w_init=initializer, with_bias=False)

pprint.pprint(nn.get_parameters())
pprint.pprint(nn.get_parameters()['affine/W'].d)

# generate data in the x_range
x.d = np.arange(x_range[0], x_range[1], (x_range[1]-x_range[0])/x_size)
pprint.pprint(x.d)

# forward pass
y.forward()

OrderedDict([('affine/W',
              <Variable((5, 1), need_grad=True) at 0x7fac590e7c50>)])
array([[-0.06689208],
       [ 0.01002087],
       [ 0.07217436],
       [ 0.02358674],
       [ 0.08924928]])
array([[-1. , -0.6, -0.2,  0.2,  0.6]])


In [4]:
pprint.pprint(y.d)

array([[0.10471159]], dtype=float32)


In [5]:
simple_model_affine = 'simple_model_affine'
nnp_file_name = os.path.join(data_directory, '%s.nnp' % simple_model_affine)
batch_size = 1
content = save_nnp(nnp_file_name, nn_name=simple_model_affine, input={'x': x}, output={'y': y}, batchsize=batch_size)
print(content)

2020-05-05 16:46:58,868 [nnabla][INFO]: Saving ./models/simple_model_affine.nnp as nnp
2020-05-05 16:46:58,869 [nnabla][INFO]: Saving /tmp/tmpwk_htgsh/network.nntxt as prototxt
2020-05-05 16:46:58,871 [nnabla][INFO]: Parameter save (.protobuf): /tmp/tmpwk_htgsh/parameter.protobuf


{'networks': [{'name': 'simple_model_affine', 'batch_size': 1, 'outputs': {'y': <Variable((1, 1), need_grad=True) at 0x7fac2e96d290>}, 'names': {'x': <Variable((1, 5), need_grad=False) at 0x7fac40027a10>}}], 'executors': [{'name': 'Runtime', 'network': 'simple_model_affine', 'data': ['x'], 'output': ['y']}]}


## RELU

In [6]:
nn.parameter.clear_parameters()
rng = np.random.seed(11579)
initializer = I.UniformInitializer((-0.1, 0.1), rng=rng)

x_size = 5
x_range = (-1.0, 1.0)

x = nn.Variable((1, x_size))          # input tensor is just a vector of x_size floats
y0 = PF.affine(x, 1, w_init=initializer, with_bias=False)
y = F.relu(y0)   # output is probs for 3 classes

pprint.pprint(nn.get_parameters())
pprint.pprint(nn.get_parameters()['affine/W'].d)

# generate data in the x_range
x.d = np.arange(x_range[0], x_range[1], (x_range[1]-x_range[0])/x_size)
pprint.pprint(x.d)

# forward pass
y.forward()

OrderedDict([('affine/W',
              <Variable((5, 1), need_grad=True) at 0x7fac2e80d050>)])
array([[ 0.01217159],
       [ 0.0739175 ],
       [-0.06551991],
       [-0.00955659],
       [ 0.00522653]])
array([[-1. , -0.6, -0.2,  0.2,  0.6]])


In [7]:
pprint.pprint(y0.d)
pprint.pprint(y.d)

array([[-0.04219351]], dtype=float32)
array([[0.]], dtype=float32)


In [8]:
simple_model_relu = 'simple_model_relu'
nnp_file_name = os.path.join(data_directory, '%s.nnp' % simple_model_relu)
batch_size = 1
content = save_nnp(nnp_file_name, nn_name=simple_model_relu, input={'x': x}, output={'y0':y0, 'y': y}, batchsize=batch_size)
print(content)

2020-05-05 16:46:58,890 [nnabla][INFO]: Saving ./models/simple_model_relu.nnp as nnp
2020-05-05 16:46:58,891 [nnabla][INFO]: Saving /tmp/tmptrbzip4y/network.nntxt as prototxt
2020-05-05 16:46:58,894 [nnabla][INFO]: Parameter save (.protobuf): /tmp/tmptrbzip4y/parameter.protobuf


{'networks': [{'name': 'simple_model_relu', 'batch_size': 1, 'outputs': {'y0': <Variable((1, 1), need_grad=True) at 0x7fac2e80d110>, 'y': <Variable((1, 1), need_grad=True) at 0x7fac2e96dfb0>}, 'names': {'x': <Variable((1, 5), need_grad=False) at 0x7fac590e7c50>}}], 'executors': [{'name': 'Runtime', 'network': 'simple_model_relu', 'data': ['x'], 'output': ['y0', 'y']}]}


## Sigmoid

In [9]:
nn.parameter.clear_parameters()
rng = np.random.seed(1393)
initializer = I.UniformInitializer((-0.1, 0.1), rng=rng)

x_size = 5
x_range = (-1.0, 1.0)

x = nn.Variable((1, x_size))          # input tensor is just a vector of x_size floats
y0 = PF.affine(x, 1, w_init=initializer, with_bias=False)
y = F.sigmoid(y0)   # output is probs for 3 classes

pprint.pprint(nn.get_parameters())
pprint.pprint(nn.get_parameters()['affine/W'].d)

# generate data in the x_range
x.d = np.arange(x_range[0], x_range[1], (x_range[1]-x_range[0])/x_size)
pprint.pprint(x.d)

# forward pass
y.forward()

OrderedDict([('affine/W',
              <Variable((5, 1), need_grad=True) at 0x7fac2e96d650>)])
array([[-0.01273317],
       [ 0.05659582],
       [ 0.01842164],
       [-0.04010906],
       [ 0.07028222]])
array([[-1. , -0.6, -0.2,  0.2,  0.6]])


In [10]:
pprint.pprint(y0.d)
pprint.pprint(y.d)

array([[0.00923887]], dtype=float32)
array([[0.5023097]], dtype=float32)


In [11]:
simple_model_sigmoid = 'simple_model_sigmoid'
nnp_file_name = os.path.join(data_directory, '%s.nnp' % simple_model_sigmoid)
batch_size = 1
content = save_nnp(nnp_file_name, nn_name=simple_model_sigmoid, input={'x': x}, output={'y0': y0, 'y': y}, batchsize=batch_size)
print(content)

2020-05-05 16:46:58,920 [nnabla][INFO]: Saving ./models/simple_model_sigmoid.nnp as nnp
2020-05-05 16:46:58,924 [nnabla][INFO]: Saving /tmp/tmp3satvhie/network.nntxt as prototxt
2020-05-05 16:46:58,928 [nnabla][INFO]: Parameter save (.protobuf): /tmp/tmp3satvhie/parameter.protobuf


{'networks': [{'name': 'simple_model_sigmoid', 'batch_size': 1, 'outputs': {'y0': <Variable((1, 1), need_grad=True) at 0x7fac2e944fb0>, 'y': <Variable((1, 1), need_grad=True) at 0x7fac2e96d6b0>}, 'names': {'x': <Variable((1, 5), need_grad=False) at 0x7fac2e96dad0>}}], 'executors': [{'name': 'Runtime', 'network': 'simple_model_sigmoid', 'data': ['x'], 'output': ['y0', 'y']}]}


## Tanh

In [12]:
nn.parameter.clear_parameters()
rng = np.random.seed(8853)
initializer = I.UniformInitializer((-0.1, 0.1), rng=rng)

x_size = 5
x_range = (-1.0, 1.0)

x = nn.Variable((1, x_size))          # input tensor is just a vector of x_size floats
y0 = PF.affine(x, 1, w_init=initializer, with_bias=False)
y = F.tanh(y0)   # output is probs for 3 classes

pprint.pprint(nn.get_parameters())
pprint.pprint(nn.get_parameters()['affine/W'].d)

# generate data in the x_range
x.d = np.arange(x_range[0], x_range[1], (x_range[1]-x_range[0])/x_size)
pprint.pprint(x.d)

# forward pass
y.forward()

OrderedDict([('affine/W',
              <Variable((5, 1), need_grad=True) at 0x7fac2e821170>)])
array([[-0.08689096],
       [ 0.00578396],
       [-0.08795961],
       [ 0.05258294],
       [ 0.01774052]])
array([[-1. , -0.6, -0.2,  0.2,  0.6]])


In [13]:
pprint.pprint(y0.d)
pprint.pprint(y.d)

array([[0.1221734]], dtype=float32)
array([[0.12156913]], dtype=float32)


In [14]:
simple_model_tanh = 'simple_model_tanh'
nnp_file_name = os.path.join(data_directory, '%s.nnp' % simple_model_tanh)
batch_size = 1
content = save_nnp(nnp_file_name, nn_name=simple_model_tanh, input={'x': x}, output={'y0': y0, 'y': y}, batchsize=batch_size)
print(content)

2020-05-05 16:46:58,958 [nnabla][INFO]: Saving ./models/simple_model_tanh.nnp as nnp
2020-05-05 16:46:58,962 [nnabla][INFO]: Saving /tmp/tmpprr7z4et/network.nntxt as prototxt
2020-05-05 16:46:58,965 [nnabla][INFO]: Parameter save (.protobuf): /tmp/tmpprr7z4et/parameter.protobuf


{'networks': [{'name': 'simple_model_tanh', 'batch_size': 1, 'outputs': {'y0': <Variable((1, 1), need_grad=True) at 0x7fac2e821110>, 'y': <Variable((1, 1), need_grad=True) at 0x7fac2e80de90>}, 'names': {'x': <Variable((1, 5), need_grad=False) at 0x7fac2e96d650>}}], 'executors': [{'name': 'Runtime', 'network': 'simple_model_tanh', 'data': ['x'], 'output': ['y0', 'y']}]}


## SoftMax

In [15]:
nn.parameter.clear_parameters()
rng = np.random.seed(63452)
initializer = I.UniformInitializer((-0.1, 0.1), rng=rng)

x_size = 5
x_range = (-1.0, 1.0)

x = nn.Variable((1, x_size))          # input tensor is just a vector of 5 floats
y0 = PF.affine(x, 1, w_init=initializer, with_bias=False)
y = F.softmax(y0)   # output is probs for 3 classes

pprint.pprint(nn.get_parameters())
pprint.pprint(nn.get_parameters()['affine/W'].d)

# generate data in the x_range
x.d = np.arange(x_range[0], x_range[1], (x_range[1]-x_range[0])/x_size)
pprint.pprint(x.d)

# forward pass
y.forward()

OrderedDict([('affine/W',
              <Variable((5, 1), need_grad=True) at 0x7fac2e80dbf0>)])
array([[-0.00840704],
       [-0.02306222],
       [-0.04123034],
       [-0.06403097],
       [ 0.02346617]])
array([[-1. , -0.6, -0.2,  0.2,  0.6]])


In [16]:
pprint.pprint(y0.d)
pprint.pprint(y.d)

array([[0.03176394]], dtype=float32)
array([[1.]], dtype=float32)


In [17]:
simple_model_softmax = 'simple_model_softmax'
nnp_file_name = os.path.join(data_directory, '%s.nnp' % simple_model_softmax)
batch_size = 1
content = save_nnp(nnp_file_name, nn_name=simple_model_softmax, input={'x': x}, output={'y0': y0, 'y': y}, batchsize=batch_size)
print(content)

2020-05-05 16:46:58,988 [nnabla][INFO]: Saving ./models/simple_model_softmax.nnp as nnp
2020-05-05 16:46:58,990 [nnabla][INFO]: Saving /tmp/tmpuycczmaf/network.nntxt as prototxt
2020-05-05 16:46:58,994 [nnabla][INFO]: Parameter save (.protobuf): /tmp/tmpuycczmaf/parameter.protobuf


{'networks': [{'name': 'simple_model_softmax', 'batch_size': 1, 'outputs': {'y0': <Variable((1, 1), need_grad=True) at 0x7fac2e80dd70>, 'y': <Variable((1, 1), need_grad=True) at 0x7fac2e80dcb0>}, 'names': {'x': <Variable((1, 5), need_grad=False) at 0x7fac2e80df50>}}], 'executors': [{'name': 'Runtime', 'network': 'simple_model_softmax', 'data': ['x'], 'output': ['y0', 'y']}]}


# Convert models

## Convert NNP to NNB

In [18]:
# Convert from NNP to NNB
import subprocess, time

models = [
    simple_model_affine,
    simple_model_relu,
    simple_model_sigmoid, 
    simple_model_tanh,
    simple_model_softmax
]

# file format conversion
for model_name in models:
    nnp_fname = os.path.join(data_directory, '%s.nnp' % model_name)
    nnb_fname = os.path.join(data_directory, '%s.nnb' % model_name)
    out = subprocess.Popen(['nnabla_cli', 'convert', '-b', '%d' % batch_size, nnp_fname, nnb_fname])

time.sleep(5)

# verification
for model_name in models:
    nnp_fname = os.path.join(data_directory, '%s.nnp' % model_name)
    nnb_fname = os.path.join(data_directory, '%s.nnb' % model_name)
    assert(os.path.exists(nnb_fname))
    assert(os.path.isfile(nnb_fname))    

## Convert NNB to C-style
This conversion uses the bin2array https://github.com/Jamesits/bin2array

In [19]:
# file format conversion
for model_name in models:
    nnb_fname = os.path.join(data_directory, '%s.nnb' % model_name)
    c_header_fname = os.path.join(data_directory, '%s.h' % model_name)
    out = subprocess.Popen(['python3', 'bin2array/bin2array.py', '-O', c_header_fname, nnb_fname])

time.sleep(5)
    
# verification
for model_name in models:
    c_header_fname = os.path.join(data_directory, '%s.h' % model_name)
    assert(os.path.exists(c_header_fname))
    assert(os.path.isfile(c_header_fname))        

# Generate test data

In [29]:
x_size = 5
x_range = (-10.0, 10.0)
n_samples = 10
test_c_header_fname = os.path.join(data_directory, 'test_data.h')

# generate data in the x_range
a = np.arange(x_range[0], x_range[1], (x_range[1]-x_range[0])/(x_size*n_samples))
b = np.reshape(a, (-1, 5))
c_str = ',\n'.join([','.join([str(e) for e in row]) for row in b])

with open(test_c_header_fname, 'w') as f:
    f.write(c_str)