# Single Operations

In [1]:
import nnabla as nn
import nnabla.functions as F
import nnabla.parametric_functions as PF
import numpy as np
import nnabla.initializer as I
from save_nnp import save_nnp

import pprint

2020-05-15 12:01:59,832 [nnabla][INFO]: Initializing CPU extension...


In [2]:
import pathlib, os
data_directory='./models'
pathlib.Path(data_directory).mkdir(parents=True, exist_ok=True)

x_size = 10

## RELU

In [3]:
nn.parameter.clear_parameters()
x_range = (-1.0, 1.0)
x = nn.Variable((1, 1))          # input tensor is just a vector of 1 float
y = F.relu(x)   # output

# generate data in the x_range
for v in np.arange(x_range[0], x_range[1], (x_range[1]-x_range[0])/x_size):
    x.d = v
    # forward pass
    y.forward()
    pprint.pprint('%0.2f ==> %0.2f' % (x.d, y.d))

'-1.00 ==> 0.00'
'-0.80 ==> 0.00'
'-0.60 ==> 0.00'
'-0.40 ==> 0.00'
'-0.20 ==> 0.00'
'-0.00 ==> 0.00'
'0.20 ==> 0.20'
'0.40 ==> 0.40'
'0.60 ==> 0.60'
'0.80 ==> 0.80'


In [4]:
simple_relu = 'simple_relu'
nnp_file_name = os.path.join(data_directory, '%s.nnp' % simple_relu)
batch_size = 1
content = save_nnp(nnp_file_name, nn_name=simple_relu, input={'x': x}, output={'y': y}, batchsize=batch_size)
print(content)

2020-05-15 12:02:00,158 [nnabla][INFO]: Saving ./models/simple_relu.nnp as nnp
2020-05-15 12:02:00,159 [nnabla][INFO]: Saving /tmp/tmpt54_fksn/network.nntxt as prototxt
2020-05-15 12:02:00,161 [nnabla][INFO]: Parameter save (.protobuf): /tmp/tmpt54_fksn/parameter.protobuf


{'networks': [{'name': 'simple_relu', 'batch_size': 1, 'outputs': {'y': <Variable((1, 1), need_grad=False) at 0x7f3c57ed2cb0>}, 'names': {'x': <Variable((1, 1), need_grad=False) at 0x7f3c57ed2d70>}}], 'executors': [{'name': 'Runtime', 'network': 'simple_relu', 'data': ['x'], 'output': ['y']}]}


## Sigmoid

In [5]:
nn.parameter.clear_parameters()
x_range = (-1.0, 1.0)
x = nn.Variable((1, 1))          # input tensor is just a vector of 1 float
y = F.sigmoid(x)   # output

# generate data in the x_range
for v in np.arange(x_range[0], x_range[1], (x_range[1]-x_range[0])/x_size):
    x.d = v
    # forward pass
    y.forward()
    pprint.pprint('%0.2f ==> %0.2f' % (x.d, y.d))

'-1.00 ==> 0.27'
'-0.80 ==> 0.31'
'-0.60 ==> 0.35'
'-0.40 ==> 0.40'
'-0.20 ==> 0.45'
'-0.00 ==> 0.50'
'0.20 ==> 0.55'
'0.40 ==> 0.60'
'0.60 ==> 0.65'
'0.80 ==> 0.69'


In [6]:
simple_sigmoid = 'simple_sigmoid'
nnp_file_name = os.path.join(data_directory, '%s.nnp' % simple_sigmoid)
batch_size = 1
content = save_nnp(nnp_file_name, nn_name=simple_sigmoid, input={'x': x}, output={'y': y}, batchsize=batch_size)
print(content)

2020-05-15 12:02:00,177 [nnabla][INFO]: Saving ./models/simple_sigmoid.nnp as nnp
2020-05-15 12:02:00,178 [nnabla][INFO]: Saving /tmp/tmp9tvs6q2h/network.nntxt as prototxt
2020-05-15 12:02:00,180 [nnabla][INFO]: Parameter save (.protobuf): /tmp/tmp9tvs6q2h/parameter.protobuf


{'networks': [{'name': 'simple_sigmoid', 'batch_size': 1, 'outputs': {'y': <Variable((1, 1), need_grad=False) at 0x7f3c57d80110>}, 'names': {'x': <Variable((1, 1), need_grad=False) at 0x7f3c57d80410>}}], 'executors': [{'name': 'Runtime', 'network': 'simple_sigmoid', 'data': ['x'], 'output': ['y']}]}


## Tanh

In [7]:
nn.parameter.clear_parameters()
x_range = (-1.0, 1.0)
x = nn.Variable((1, 1))          # input tensor is just a vector of 1 float
y = F.tanh(x)   # output

# generate data in the x_range
for v in np.arange(x_range[0], x_range[1], (x_range[1]-x_range[0])/x_size):
    x.d = v
    # forward pass
    y.forward()
    pprint.pprint('%0.2f ==> %0.2f' % (x.d, y.d))

'-1.00 ==> -0.76'
'-0.80 ==> -0.66'
'-0.60 ==> -0.54'
'-0.40 ==> -0.38'
'-0.20 ==> -0.20'
'-0.00 ==> -0.00'
'0.20 ==> 0.20'
'0.40 ==> 0.38'
'0.60 ==> 0.54'
'0.80 ==> 0.66'


In [8]:
simple_tanh = 'simple_tanh'
nnp_file_name = os.path.join(data_directory, '%s.nnp' % simple_tanh)
batch_size = 1
content = save_nnp(nnp_file_name, nn_name=simple_tanh, input={'x': x}, output={'y': y}, batchsize=batch_size)
print(content)

2020-05-15 12:02:00,204 [nnabla][INFO]: Saving ./models/simple_tanh.nnp as nnp
2020-05-15 12:02:00,207 [nnabla][INFO]: Saving /tmp/tmpwv0er626/network.nntxt as prototxt
2020-05-15 12:02:00,210 [nnabla][INFO]: Parameter save (.protobuf): /tmp/tmpwv0er626/parameter.protobuf


{'networks': [{'name': 'simple_tanh', 'batch_size': 1, 'outputs': {'y': <Variable((1, 1), need_grad=False) at 0x7f3c57d80b30>}, 'names': {'x': <Variable((1, 1), need_grad=False) at 0x7f3c57d80a70>}}], 'executors': [{'name': 'Runtime', 'network': 'simple_tanh', 'data': ['x'], 'output': ['y']}]}


## SoftMax

In [9]:
import numpy

x_size = 2
nn.parameter.clear_parameters()
x_range = (-1.0, 1.0)
x = nn.Variable((1, 2))          # input tensor is just a vector of 1 float
y = F.softmax(x)   # output

# generate data in the x_range
for v0 in np.arange(x_range[0], x_range[1], (x_range[1]-x_range[0])/x_size):
    for v1 in np.arange(x_range[0], x_range[1], (x_range[1]-x_range[0])/x_size):
        x.d = numpy.array([v0, v1])
        # forward pass
        y.forward()
        pprint.pprint('%s ==> %s' % (str(x.d), str(y.d)))

'[[-1. -1.]] ==> [[0.5 0.5]]'
'[[-1.  0.]] ==> [[0.26894143 0.7310586 ]]'
'[[ 0. -1.]] ==> [[0.7310586  0.26894143]]'
'[[0. 0.]] ==> [[0.5 0.5]]'


In [10]:
simple_softmax = 'simple_softmax'
nnp_file_name = os.path.join(data_directory, '%s.nnp' % simple_softmax)
batch_size = 1
content = save_nnp(nnp_file_name, nn_name=simple_softmax, input={'x': x}, output={'y': y}, batchsize=batch_size)
print(content)

2020-05-15 12:02:00,233 [nnabla][INFO]: Saving ./models/simple_softmax.nnp as nnp
2020-05-15 12:02:00,234 [nnabla][INFO]: Saving /tmp/tmp6l1esuz4/network.nntxt as prototxt
2020-05-15 12:02:00,236 [nnabla][INFO]: Parameter save (.protobuf): /tmp/tmp6l1esuz4/parameter.protobuf


{'networks': [{'name': 'simple_softmax', 'batch_size': 1, 'outputs': {'y': <Variable((1, 2), need_grad=False) at 0x7f3c57d80530>}, 'names': {'x': <Variable((1, 2), need_grad=False) at 0x7f3c57ed2cb0>}}], 'executors': [{'name': 'Runtime', 'network': 'simple_softmax', 'data': ['x'], 'output': ['y']}]}


# Single Neuron Networks

In [11]:
import nnabla as nn
import nnabla.functions as F
import nnabla.parametric_functions as PF
import numpy as np
import nnabla.initializer as I
from save_nnp import save_nnp

import pprint

In [12]:
import pathlib, os
data_directory='./models'
pathlib.Path(data_directory).mkdir(parents=True, exist_ok=True)

x_size = 5

## Affine

In [13]:
nn.parameter.clear_parameters()
rng = np.random.seed(2345)
initializer = I.UniformInitializer((-0.1, 0.1), rng=rng)

x_range = (-1.0, 1.0)
x = nn.Variable((1, x_size))          # input tensor is just a vector of x_size floats
y = PF.affine(x, 1, w_init=initializer, with_bias=False)

pprint.pprint(nn.get_parameters())
pprint.pprint(nn.get_parameters()['affine/W'].d)

# generate data in the x_range
x.d = np.arange(x_range[0], x_range[1], (x_range[1]-x_range[0])/x_size)
pprint.pprint(x.d)

# forward pass
y.forward()

OrderedDict([('affine/W',
              <Variable((5, 1), need_grad=True) at 0x7f3c57d94b30>)])
array([[-0.06689208],
       [ 0.01002087],
       [ 0.07217436],
       [ 0.02358674],
       [ 0.08924928]])
array([[-1. , -0.6, -0.2,  0.2,  0.6]])


In [14]:
pprint.pprint(y.d)

array([[0.10471159]], dtype=float32)


In [15]:
simple_model_affine = 'simple_model_affine'
nnp_file_name = os.path.join(data_directory, '%s.nnp' % simple_model_affine)
batch_size = 1
content = save_nnp(nnp_file_name, nn_name=simple_model_affine, input={'x': x}, output={'y': y}, batchsize=batch_size)
print(content)

2020-05-15 12:02:00,281 [nnabla][INFO]: Saving ./models/simple_model_affine.nnp as nnp
2020-05-15 12:02:00,282 [nnabla][INFO]: Saving /tmp/tmpv05vbeq8/network.nntxt as prototxt
2020-05-15 12:02:00,286 [nnabla][INFO]: Parameter save (.protobuf): /tmp/tmpv05vbeq8/parameter.protobuf


{'networks': [{'name': 'simple_model_affine', 'batch_size': 1, 'outputs': {'y': <Variable((1, 1), need_grad=True) at 0x7f3c57d94bf0>}, 'names': {'x': <Variable((1, 5), need_grad=False) at 0x7f3c5e152d70>}}], 'executors': [{'name': 'Runtime', 'network': 'simple_model_affine', 'data': ['x'], 'output': ['y']}]}


## RELU

In [16]:
nn.parameter.clear_parameters()
rng = np.random.seed(11579)
initializer = I.UniformInitializer((-0.1, 0.1), rng=rng)

x_range = (-1.0, 1.0)
x = nn.Variable((1, x_size))          # input tensor is just a vector of x_size floats
y0 = PF.affine(x, 1, w_init=initializer, with_bias=False)
y = F.relu(y0)   # output

pprint.pprint(nn.get_parameters())
pprint.pprint(nn.get_parameters()['affine/W'].d)

# generate data in the x_range
x.d = np.arange(x_range[0], x_range[1], (x_range[1]-x_range[0])/x_size)
pprint.pprint(x.d)

# forward pass
y.forward()

OrderedDict([('affine/W',
              <Variable((5, 1), need_grad=True) at 0x7f3c57d947d0>)])
array([[ 0.01217159],
       [ 0.0739175 ],
       [-0.06551991],
       [-0.00955659],
       [ 0.00522653]])
array([[-1. , -0.6, -0.2,  0.2,  0.6]])


In [17]:
pprint.pprint(y0.d)
pprint.pprint(y.d)

array([[-0.04219351]], dtype=float32)
array([[0.]], dtype=float32)


In [18]:
simple_model_relu = 'simple_model_relu'
nnp_file_name = os.path.join(data_directory, '%s.nnp' % simple_model_relu)
batch_size = 1
content = save_nnp(nnp_file_name, nn_name=simple_model_relu, input={'x': x}, output={'y0':y0, 'y': y}, batchsize=batch_size)
print(content)

2020-05-15 12:02:00,325 [nnabla][INFO]: Saving ./models/simple_model_relu.nnp as nnp
2020-05-15 12:02:00,327 [nnabla][INFO]: Saving /tmp/tmp2a1t611g/network.nntxt as prototxt
2020-05-15 12:02:00,331 [nnabla][INFO]: Parameter save (.protobuf): /tmp/tmp2a1t611g/parameter.protobuf


{'networks': [{'name': 'simple_model_relu', 'batch_size': 1, 'outputs': {'y0': <Variable((1, 1), need_grad=True) at 0x7f3c57d94770>, 'y': <Variable((1, 1), need_grad=True) at 0x7f3c57d94890>}, 'names': {'x': <Variable((1, 5), need_grad=False) at 0x7f3c57d94b30>}}], 'executors': [{'name': 'Runtime', 'network': 'simple_model_relu', 'data': ['x'], 'output': ['y0', 'y']}]}


## Sigmoid

In [19]:
nn.parameter.clear_parameters()
rng = np.random.seed(1393)
initializer = I.UniformInitializer((-0.1, 0.1), rng=rng)

x_range = (-1.0, 1.0)
x = nn.Variable((1, x_size))          # input tensor is just a vector of x_size floats
y0 = PF.affine(x, 1, w_init=initializer, with_bias=False)
y = F.sigmoid(y0)   # output

pprint.pprint(nn.get_parameters())
pprint.pprint(nn.get_parameters()['affine/W'].d)

# generate data in the x_range
x.d = np.arange(x_range[0], x_range[1], (x_range[1]-x_range[0])/x_size)
pprint.pprint(x.d)

# forward pass
y.forward()

OrderedDict([('affine/W',
              <Variable((5, 1), need_grad=True) at 0x7f3c57daabf0>)])
array([[-0.01273317],
       [ 0.05659582],
       [ 0.01842164],
       [-0.04010906],
       [ 0.07028222]])
array([[-1. , -0.6, -0.2,  0.2,  0.6]])


In [20]:
pprint.pprint(y0.d)
pprint.pprint(y.d)

array([[0.00923887]], dtype=float32)
array([[0.5023097]], dtype=float32)


In [21]:
simple_model_sigmoid = 'simple_model_sigmoid'
nnp_file_name = os.path.join(data_directory, '%s.nnp' % simple_model_sigmoid)
batch_size = 1
content = save_nnp(nnp_file_name, nn_name=simple_model_sigmoid, input={'x': x}, output={'y0': y0, 'y': y}, batchsize=batch_size)
print(content)

2020-05-15 12:02:00,370 [nnabla][INFO]: Saving ./models/simple_model_sigmoid.nnp as nnp
2020-05-15 12:02:00,371 [nnabla][INFO]: Saving /tmp/tmp978zi2wz/network.nntxt as prototxt
2020-05-15 12:02:00,376 [nnabla][INFO]: Parameter save (.protobuf): /tmp/tmp978zi2wz/parameter.protobuf


{'networks': [{'name': 'simple_model_sigmoid', 'batch_size': 1, 'outputs': {'y0': <Variable((1, 1), need_grad=True) at 0x7f3c57daad10>, 'y': <Variable((1, 1), need_grad=True) at 0x7f3c57daad70>}, 'names': {'x': <Variable((1, 5), need_grad=False) at 0x7f3c57d947d0>}}], 'executors': [{'name': 'Runtime', 'network': 'simple_model_sigmoid', 'data': ['x'], 'output': ['y0', 'y']}]}


## Tanh

In [22]:
nn.parameter.clear_parameters()
rng = np.random.seed(8853)
initializer = I.UniformInitializer((-0.1, 0.1), rng=rng)

x_range = (-1.0, 1.0)
x = nn.Variable((1, x_size))          # input tensor is just a vector of x_size floats
y0 = PF.affine(x, 1, w_init=initializer, with_bias=False)
y = F.tanh(y0)   # output

pprint.pprint(nn.get_parameters())
pprint.pprint(nn.get_parameters()['affine/W'].d)

# generate data in the x_range
x.d = np.arange(x_range[0], x_range[1], (x_range[1]-x_range[0])/x_size)
pprint.pprint(x.d)

# forward pass
y.forward()

OrderedDict([('affine/W',
              <Variable((5, 1), need_grad=True) at 0x7f3c57db9950>)])
array([[-0.08689096],
       [ 0.00578396],
       [-0.08795961],
       [ 0.05258294],
       [ 0.01774052]])
array([[-1. , -0.6, -0.2,  0.2,  0.6]])


In [23]:
pprint.pprint(y0.d)
pprint.pprint(y.d)

array([[0.1221734]], dtype=float32)
array([[0.12156913]], dtype=float32)


In [24]:
simple_model_tanh = 'simple_model_tanh'
nnp_file_name = os.path.join(data_directory, '%s.nnp' % simple_model_tanh)
batch_size = 1
content = save_nnp(nnp_file_name, nn_name=simple_model_tanh, input={'x': x}, output={'y0': y0, 'y': y}, batchsize=batch_size)
print(content)

2020-05-15 12:02:00,413 [nnabla][INFO]: Saving ./models/simple_model_tanh.nnp as nnp
2020-05-15 12:02:00,415 [nnabla][INFO]: Saving /tmp/tmp3b6s5vaq/network.nntxt as prototxt
2020-05-15 12:02:00,419 [nnabla][INFO]: Parameter save (.protobuf): /tmp/tmp3b6s5vaq/parameter.protobuf


{'networks': [{'name': 'simple_model_tanh', 'batch_size': 1, 'outputs': {'y0': <Variable((1, 1), need_grad=True) at 0x7f3c57ed2d70>, 'y': <Variable((1, 1), need_grad=True) at 0x7f3c57db9890>}, 'names': {'x': <Variable((1, 5), need_grad=False) at 0x7f3c57daabf0>}}], 'executors': [{'name': 'Runtime', 'network': 'simple_model_tanh', 'data': ['x'], 'output': ['y0', 'y']}]}


## SoftMax

In [25]:
nn.parameter.clear_parameters()
rng = np.random.seed(63452)
initializer = I.UniformInitializer((-0.1, 0.1), rng=rng)

y0_size = 2
x_range = (-1.0, 1.0)
x = nn.Variable((1, x_size))          # input tensor is just a vector of 5 floats
y0 = PF.affine(x, y0_size, w_init=initializer, with_bias=False)
y = F.softmax(y0)   # output

pprint.pprint(nn.get_parameters())
pprint.pprint(nn.get_parameters()['affine/W'].d)

# generate data in the x_range
x.d = np.arange(x_range[0], x_range[1], (x_range[1]-x_range[0])/x_size)
pprint.pprint(x.d)

# forward pass
y.forward()

OrderedDict([('affine/W',
              <Variable((5, 2), need_grad=True) at 0x7f3c57d944d0>)])
array([[-0.00840704, -0.02306222],
       [-0.04123034, -0.06403097],
       [ 0.02346617, -0.05210479],
       [-0.09995786,  0.05643672],
       [ 0.00512868, -0.01903969]])
array([[-1. , -0.6, -0.2,  0.2,  0.6]])


In [26]:
pprint.pprint(y0.d)
pprint.pprint(y.d)

array([[0.01153764, 0.07176528]], dtype=float32)
array([[0.48494762, 0.5150523 ]], dtype=float32)


In [27]:
simple_model_softmax = 'simple_model_softmax'
nnp_file_name = os.path.join(data_directory, '%s.nnp' % simple_model_softmax)
batch_size = 1
content = save_nnp(nnp_file_name, nn_name=simple_model_softmax, input={'x': x}, output={'y0': y0, 'y': y}, batchsize=batch_size)
print(content)

2020-05-15 12:02:00,468 [nnabla][INFO]: Saving ./models/simple_model_softmax.nnp as nnp
2020-05-15 12:02:00,469 [nnabla][INFO]: Saving /tmp/tmpd8wqqpwt/network.nntxt as prototxt
2020-05-15 12:02:00,476 [nnabla][INFO]: Parameter save (.protobuf): /tmp/tmpd8wqqpwt/parameter.protobuf


{'networks': [{'name': 'simple_model_softmax', 'batch_size': 1, 'outputs': {'y0': <Variable((1, 2), need_grad=True) at 0x7f3c57daab30>, 'y': <Variable((1, 2), need_grad=True) at 0x7f3c57daa0b0>}, 'names': {'x': <Variable((1, 5), need_grad=False) at 0x7f3c57daa6b0>}}], 'executors': [{'name': 'Runtime', 'network': 'simple_model_softmax', 'data': ['x'], 'output': ['y0', 'y']}]}


# Convert models

## Convert NNP to NNB

In [28]:
# Convert from NNP to NNB
import subprocess, time

models = [
    simple_model_affine,
    simple_model_relu,
    simple_model_sigmoid, 
    simple_model_tanh,
    simple_model_softmax,
    simple_relu,
    simple_sigmoid, 
    simple_tanh,
    simple_softmax
]

# file format conversion
for model_name in models:
    nnp_fname = os.path.join(data_directory, '%s.nnp' % model_name)
    nnb_fname = os.path.join(data_directory, '%s.nnb' % model_name)
    out = subprocess.Popen(['nnabla_cli', 'convert', '-b', '%d' % batch_size, nnp_fname, nnb_fname])

time.sleep(5)

# verification
for model_name in models:
    nnp_fname = os.path.join(data_directory, '%s.nnp' % model_name)
    nnb_fname = os.path.join(data_directory, '%s.nnb' % model_name)
    assert(os.path.exists(nnb_fname))
    assert(os.path.isfile(nnb_fname))    

## Convert NNB to C-style
This conversion uses the bin2array https://github.com/Jamesits/bin2array

In [29]:
# file format conversion
for model_name in models:
    nnb_fname = os.path.join(data_directory, '%s.nnb' % model_name)
    c_header_fname = os.path.join(data_directory, '%s.h' % model_name)
    out = subprocess.Popen(['python3', 'bin2array/bin2array.py', '-O', c_header_fname, nnb_fname])

time.sleep(5)
    
# verification
for model_name in models:
    c_header_fname = os.path.join(data_directory, '%s.h' % model_name)
    assert(os.path.exists(c_header_fname))
    assert(os.path.isfile(c_header_fname))        

# Generate test data

In [30]:
x_range = (-10.0, 10.0)
n_samples = 10
test_c_header_fname = os.path.join(data_directory, 'test_data.h')

# generate data in the x_range
a = np.arange(x_range[0], x_range[1], (x_range[1]-x_range[0])/(x_size*n_samples))
b = np.reshape(a, (-1, x_size))
c_str = ',\n'.join([','.join([str(e) for e in row]) for row in b])

with open(test_c_header_fname, 'w') as f:
    f.write(c_str)

time.sleep(5)
    
# verification
assert(os.path.exists(test_c_header_fname))
assert(os.path.isfile(test_c_header_fname))            

# Load models, run inferences

In [31]:
from nnabla.utils.nnp_graph import NnpLoader

nn.parameter.clear_parameters()

for model_name in models:
    nnp_fname = os.path.join(data_directory, '%s.nnp' % model_name)
    # Read a .nnp file.
    nnp = NnpLoader(nnp_fname)
    nw_name = nnp.get_network_names()[0]
    pprint.pprint('%s %s %s' % ('#' * 10, nw_name, '#' * 10))
    net = nnp.get_network(nw_name)
    pprint.pprint(net.variables)
    x = net.inputs['x']
    y = net.outputs['y']
    pprint.pprint(x)
    pprint.pprint(y)
    for d in b:
        x.d = d
        y.forward()
        pprint.pprint(y.d)


'########## simple_model_affine ##########'
{'affine/W': <Variable((5, 1), need_grad=True) at 0x7f3c5496d830>,
 'x': <Variable((1, 5), need_grad=False) at 0x7f3c5496d890>,
 'y': <Variable((1, 1), need_grad=True) at 0x7f3c5496dd70>}
<Variable((1, 5), need_grad=False) at 0x7f3c5496d890>
<Variable((1, 1), need_grad=True) at 0x7f3c5496dd70>
array([[-1.0485411]], dtype=float32)
array([[-0.7922627]], dtype=float32)
array([[-0.5359843]], dtype=float32)
array([[-0.279706]], dtype=float32)
array([[-0.02342759]], dtype=float32)
array([[0.23285078]], dtype=float32)
array([[0.48912913]], dtype=float32)
array([[0.7454075]], dtype=float32)
array([[1.0016859]], dtype=float32)
array([[1.2579644]], dtype=float32)
'########## simple_model_relu ##########'
{'affine/W': <Variable((5, 1), need_grad=True) at 0x7f3c5497e3b0>,
 'x': <Variable((1, 5), need_grad=False) at 0x7f3c5497e350>,
 'y': <Variable((1, 1), need_grad=True) at 0x7f3c5497e4d0>,
 'y0': <Variable((1, 1), need_grad=True) at 0x7f3c5497e470>}
<Va

ValueError: An error occurs during creation of a variable `affine/W` as a parameter variable. The error was:
----
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/nnabla/utils/nnp_graph.py", line 283, in _get_variable_or_create
    assert shape == param.shape
AssertionError

----
The parameters registered was affine/W